name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Har raat 12 baje chalega
  workflow_dispatch: # Taaki aap manual bhi chala sakein
  push:
    branches:
      - main # Main branch par push hote hi chalega

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ye line bahut zaroori hai files update karne ke liye

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: deeksha0023
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
