# 👋 Hi, I'm Diksha Kumari

<img src="https://readme-typing-svg.herokuapp.com?color=F78C6C&size=22&center=true&vCenter=true&width=500&lines=MERN+Stack+Developer;Java+DSA+Learner;Building+Projects+Daily;Future+Software+Engineer" />

---

## 🚀 About Me
- 🌱 Currently learning **MERN Stack & DSA (Java)**
- 💡 Love building real-world projects  
- 📚 Improving problem-solving skills daily  
- 🎯 Goal: Become a Software Developer  

---

## 🛠️ Tech Stack
<p>
<img src="https://skillicons.dev/icons?i=html,css,js,react,nodejs,express,mongodb,mysql,java,git,github,vscode" />
</p>

---

## 🏆 GitHub Trophies
![trophy](https://github-profile-trophy.vercel.app/?username=deeksha0023&theme=onedark)

---

## 🏆 GitHub Trophies
[![trophy](https://github-profile-trophy.vercel.app/?username=deeksha0023&theme=onedark&column=7)](https://github.com/ryo-ma/github-profile-trophy)

## 🔥 GitHub Streak
![GitHub Streak](https://streak-stats.demolab.com?user=deeksha0023&theme=tokyonight)

---

## 📊 Most Used Languages
![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=deeksha0023&layout=compact&theme=tokyonight)

---

## 🐍 Contribution Snake
![snake gif](https://raw.githubusercontent.com/deeksha0023/deeksha0023/output/github-contribution-grid-snake.svg)

---

## 🌐 Connect With Me
- 💼 LinkedIn: https://www.linkedin.com/in/deeksha-yadav-b13698281/  
- 🧠 LeetCode: https://leetcode.com/u/Deeksha__Yadav/  

---

✨ “Code. Learn. Build. Repeat.” 🔁
